Add Page | Douglas Vinicius
jeancapote/TDES2020-1N2 pull request #2
Opened 2021-06-10 22:42 UTC by Douglas-cpr

### Descrição

Foi adicionado a página do aluno Douglas Vinicius para compor a seção de colaboradores do site.

2021-06-17 21:59 UTC, fellipews7 commented
Aqui tu escreve em português né kkkk

![image](https://user-images.githubusercontent.com/78887074/122477481-2c4da300-cf9e-11eb-8349-9738ff2f716c.png)

2021-06-17 22:43 UTC, NathanBergmann reviewed
### Descrição
Cadê o arquivo index?

2021-06-17 22:51 UTC, emersonmendonca reviewed
deixei uma sugestão de mudança, mas o restante está ok.

2021-06-17 22:51 UTC, emersonmendonca commented on app/pages/douglasVinicius.html
> +            Na hora que eu fui morder aquela goiaba</p>
está faltando o resto do poema

2021-06-17 22:55 UTC, marcosvinicius2020 approved these changes
esta tudo ok

2021-07-01 22:03 UTC, jeancapote requested changes
Falta o link da page no index

2021-07-01 22:03 UTC, jeancapote commented on app/pages/douglasVinicius.html
> +    <title>Jean Page</title>
```suggestion
    <title>Douglas Page</title>
```

2021-07-01 22:03 UTC, jeancapote commented on app/pages/douglasVinicius.html
> +
```suggestion
```

2021-07-01 22:03 UTC, jeancapote commented on app/pages/douglasVinicius.html
> +
```suggestion
```

2021-07-01 22:33 UTC, Clervens approved these changes

2021-07-01 22:39 UTC, Douglas-cpr commented on app/pages/douglasVinicius.html
> +            Na hora que eu fui morder aquela goiaba</p>
Obrigado pela sugestão, porém de acordo com o problema proposto essa parte já atende o solicitado.

2021-07-01 22:40 UTC, Douglas-cpr commented on app/pages/douglasVinicius.html
> +
O padrão do projeto é com divisões de linha entre as seções, para uma melhor visualização.

2021-07-01 22:40 UTC, Douglas-cpr commented on app/pages/douglasVinicius.html
> +
O padrão do projeto é com divisões de linha entre as seções, para uma melhor visualização.

2021-07-01 22:41 UTC, merged