Add Page | andre ribeiro
jeancapote/TDES2020-1N2 pull request #21
Opened 2021-06-10 23:28 UTC by andrelribeiro15

### Descrição
Foi adicionado a página do aluno André Luiz Ribeiro para compor a seção de colaboradores do site.

2021-06-17 22:37 UTC, lleobaptista approved these changes

2021-06-17 22:37 UTC, Sidneyasjr commented on app/index.html
> +            <li><a href="pages/andreLuizRibeiro.html">André Luiz Ribeiro </a></li>
Faltou o item `Professor: Jean`

2021-06-17 22:38 UTC, Sidneyasjr requested changes
Faltou o item `Professor: Jean`

2021-06-17 22:41 UTC, DanielLFSouza reviewed
Revisão feita e o código está bom

2021-06-17 22:44 UTC, ZeeeoDaniel commented on app/index.html
> +            <li><a href="pages/andreLuizRibeiro.html">André Luiz Ribeiro </a></li>
Faltou o item Professor: Jean

2021-06-17 22:46 UTC, andrelribeiro15 commented on app/index.html
> +            <li><a href="pages/andreLuizRibeiro.html">André Luiz Ribeiro </a></li>
como assim? era pra deixar aquele então?

2021-06-17 22:49 UTC, ZeeeoDaniel requested changes
O teu arquivo tem o nome do fellipe, teria que tirar ele e botar só o seu

2021-06-17 23:12 UTC, ZeeeoDaniel requested changes
Remover a page/fellipeSchenekemberg

2021-06-17 23:13 UTC, andrelribeiro15 commented
a parte que está em vermelho foi oq eu mudei, daí não tem o nome dele e sim o meu

2021-06-17 23:27 UTC, Sidneyasjr approved these changes
Tudo Ok

2021-06-17 23:35 UTC, ZeeeoDaniel approved these changes

2021-07-01 22:48 UTC, DanielLFSouza approved these changes

2021-07-01 22:54 UTC, merged