Add Page | Henrique Vieira Sacht
jeancapote/TDES2020-1N2 pull request #24
Opened 2021-06-17 22:42 UTC by Henriquesacht

2021-06-17 22:52 UTC, Ezylpro requested changes

2021-06-17 22:52 UTC, Ezylpro commented on app/index.html
> +            <li><a href="pages/Henrique_VieiraSacht.html">Aluno: Henrique</a></li>
```suggestion
            <li><a href="pages/Henrique_VieiraSacht.html">Aluno: Henrique Vieira Sacht</a></li>
```

Nome completo seria mais apropriado

2021-06-17 22:52 UTC, Ezylpro commented on app/index.html
>              <li><a href="pages/jean_santos.html">Aluno: Jean Santos</a></li>
```suggestion
           
```

Remover linha do Aluno: Jean Santos

2021-06-17 23:02 UTC, Helena-F-O approved these changes
### Revisão
Não esqueça de comentar certinho os commits e colocar a label "enhancement".

2021-06-18 01:32 UTC, fabiobertoni commented on app/index.html
>              <li><a href="pages/jean_santos.html">Aluno: Jean Santos</a></li>
### REVISÃO

Fazer a exclusão desta linha

2021-06-18 01:32 UTC, fabiobertoni commented on app/index.html
> +            <li><a href="pages/Henrique_VieiraSacht.html">Aluno: Henrique</a></li>
### REVISÃO

Completar o sobrenome.

2021-07-01 22:41 UTC, merged