Nova pessoa gustavo wornes
jeancapote/TDES2020-1N2 pull request #4
Opened 2021-06-10 22:45 UTC by GustavoWornes

### Descrição
Foi adicionado a página do aluno Gustavo Wornes para compor a seção de colaboradores do site.

2021-06-17 22:50 UTC, 14-01-1997 approved these changes
Não localizei erros

2021-07-01 22:15 UTC, jeancapote requested changes

2021-07-01 22:15 UTC, jeancapote commented on app/index.html
> +            <li><a href="pages/gustavo_wornes.html">Professor: Gustavo Wornes</a></li>
```suggestion
            <li><a href="pages/gustavo_wornes.html">Aluno: Gustavo Wornes</a></li>
```

2021-07-01 22:24 UTC, jeancapote approved these changes

2021-07-01 22:24 UTC, merged